/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantCampaignsRouteImport } from './routes/merchant.campaigns'
import { Route as MerchantCustomersRouteImport } from './routes/merchant.customers'
import { Route as MerchantMessagesRouteImport } from './routes/merchant.messages'
import { Route as MerchantProfileRouteImport } from './routes/merchant.profile'
import { Route as MerchantWhatsappSessionsRouteImport } from './routes/merchant.whatsapp-sessions'
import { Route as MerchantCampaignsIndexRouteImport } from './routes/merchant.campaigns.index'
import { Route as MerchantCampaignsCreateRouteImport } from './routes/merchant.campaigns.create'
import { Route as MerchantCampaignsProgressRouteImport } from './routes/merchant.campaigns.progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCampaignsRoute = MerchantCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCustomersRoute = MerchantCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMessagesRoute = MerchantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantWhatsappSessionsRoute =
  MerchantWhatsappSessionsRouteImport.update({
    id: '/whatsapp-sessions',
    path: '/whatsapp-sessions',
    getParentRoute: () => MerchantRoute,
  } as any)
const MerchantCampaignsIndexRoute = MerchantCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantCampaignsRoute,
} as any)
const MerchantCampaignsCreateRoute = MerchantCampaignsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MerchantCampaignsRoute,
} as any)
const MerchantCampaignsProgressRoute =
  MerchantCampaignsProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => MerchantCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/campaigns': typeof MerchantCampaignsRouteWithChildren
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/whatsapp-sessions': typeof MerchantWhatsappSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/campaigns/create': typeof MerchantCampaignsCreateRoute
  '/merchant/campaigns/progress': typeof MerchantCampaignsProgressRoute
  '/merchant/campaigns/': typeof MerchantCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/whatsapp-sessions': typeof MerchantWhatsappSessionsRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/merchant/campaigns/create': typeof MerchantCampaignsCreateRoute
  '/merchant/campaigns/progress': typeof MerchantCampaignsProgressRoute
  '/merchant/campaigns': typeof MerchantCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/campaigns': typeof MerchantCampaignsRouteWithChildren
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/whatsapp-sessions': typeof MerchantWhatsappSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/campaigns/create': typeof MerchantCampaignsCreateRoute
  '/merchant/campaigns/progress': typeof MerchantCampaignsProgressRoute
  '/merchant/campaigns/': typeof MerchantCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/merchant'
    | '/register'
    | '/reset-password'
    | '/admin/campaigns'
    | '/admin/sessions'
    | '/admin/users'
    | '/merchant/campaigns'
    | '/merchant/customers'
    | '/merchant/messages'
    | '/merchant/profile'
    | '/merchant/whatsapp-sessions'
    | '/admin/'
    | '/merchant/'
    | '/merchant/campaigns/create'
    | '/merchant/campaigns/progress'
    | '/merchant/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/campaigns'
    | '/admin/sessions'
    | '/admin/users'
    | '/merchant/customers'
    | '/merchant/messages'
    | '/merchant/profile'
    | '/merchant/whatsapp-sessions'
    | '/admin'
    | '/merchant'
    | '/merchant/campaigns/create'
    | '/merchant/campaigns/progress'
    | '/merchant/campaigns'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/merchant'
    | '/register'
    | '/reset-password'
    | '/admin/campaigns'
    | '/admin/sessions'
    | '/admin/users'
    | '/merchant/campaigns'
    | '/merchant/customers'
    | '/merchant/messages'
    | '/merchant/profile'
    | '/merchant/whatsapp-sessions'
    | '/admin/'
    | '/merchant/'
    | '/merchant/campaigns/create'
    | '/merchant/campaigns/progress'
    | '/merchant/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/campaigns': {
      id: '/merchant/campaigns'
      path: '/campaigns'
      fullPath: '/merchant/campaigns'
      preLoaderRoute: typeof MerchantCampaignsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/customers': {
      id: '/merchant/customers'
      path: '/customers'
      fullPath: '/merchant/customers'
      preLoaderRoute: typeof MerchantCustomersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/messages': {
      id: '/merchant/messages'
      path: '/messages'
      fullPath: '/merchant/messages'
      preLoaderRoute: typeof MerchantMessagesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/profile': {
      id: '/merchant/profile'
      path: '/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/whatsapp-sessions': {
      id: '/merchant/whatsapp-sessions'
      path: '/whatsapp-sessions'
      fullPath: '/merchant/whatsapp-sessions'
      preLoaderRoute: typeof MerchantWhatsappSessionsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/campaigns/': {
      id: '/merchant/campaigns/'
      path: '/'
      fullPath: '/merchant/campaigns/'
      preLoaderRoute: typeof MerchantCampaignsIndexRouteImport
      parentRoute: typeof MerchantCampaignsRoute
    }
    '/merchant/campaigns/create': {
      id: '/merchant/campaigns/create'
      path: '/create'
      fullPath: '/merchant/campaigns/create'
      preLoaderRoute: typeof MerchantCampaignsCreateRouteImport
      parentRoute: typeof MerchantCampaignsRoute
    }
    '/merchant/campaigns/progress': {
      id: '/merchant/campaigns/progress'
      path: '/progress'
      fullPath: '/merchant/campaigns/progress'
      preLoaderRoute: typeof MerchantCampaignsProgressRouteImport
      parentRoute: typeof MerchantCampaignsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantCampaignsRouteChildren {
  MerchantCampaignsCreateRoute: typeof MerchantCampaignsCreateRoute
  MerchantCampaignsProgressRoute: typeof MerchantCampaignsProgressRoute
  MerchantCampaignsIndexRoute: typeof MerchantCampaignsIndexRoute
}

const MerchantCampaignsRouteChildren: MerchantCampaignsRouteChildren = {
  MerchantCampaignsCreateRoute: MerchantCampaignsCreateRoute,
  MerchantCampaignsProgressRoute: MerchantCampaignsProgressRoute,
  MerchantCampaignsIndexRoute: MerchantCampaignsIndexRoute,
}

const MerchantCampaignsRouteWithChildren =
  MerchantCampaignsRoute._addFileChildren(MerchantCampaignsRouteChildren)

interface MerchantRouteChildren {
  MerchantCampaignsRoute: typeof MerchantCampaignsRouteWithChildren
  MerchantCustomersRoute: typeof MerchantCustomersRoute
  MerchantMessagesRoute: typeof MerchantMessagesRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  MerchantWhatsappSessionsRoute: typeof MerchantWhatsappSessionsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantCampaignsRoute: MerchantCampaignsRouteWithChildren,
  MerchantCustomersRoute: MerchantCustomersRoute,
  MerchantMessagesRoute: MerchantMessagesRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantWhatsappSessionsRoute: MerchantWhatsappSessionsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
